kps:
  alertmanager:
    enabled: true
    alertmanagerSpec:
      secrets:
        - slack-webhook
    config:
      route:
        receiver: slack
        group_by: ['alertname','job','namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
        routes:
          - matchers:
              - 'team=cno'
              - 'service=grpc'
            receiver: slack
          - matchers:
              - 'team=cno'
              - 'service=k8s'
            receiver: slack
          - matchers:
              - 'team=cno'
              - 'service=operator'
            receiver: slack
      receivers:
        - name: slack
          slack_configs:
            - send_resolved: true
              api_url_file: /etc/alertmanager/secrets/slack-webhook/url
              channel: "#observability"
              username: "Alertmanager"
    extraSecretMounts:
      - name: slack-webhook
        secretName: slack-webhook
        mountPath: /etc/alertmanager/secrets/slack-webhook
        readOnly: true
