name: lint (monitoring)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint & jq
        run: |
          python3 -m pip install --upgrade pip
          pip3 install yamllint
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Run yamllint
        run: yamllint .
      - name: Run markdownlint
        run: npx --yes markdownlint-cli2 **/*.md
      - name: Validate JSON
        run: |
          set -e
          find . -type f -name "*.json" -print0 | xargs -0 -I{} sh -c 'jq . "{}" >/dev/null' || true

      - name: Check charts presence
        id: have_charts
        run: |
          if [ -d charts ] && ls charts | grep -q .; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install kubeconform
        if: steps.have_charts.outputs.found == 'true'
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar xz -C /usr/local/bin

      - name: Helm lint
        if: steps.have_charts.outputs.found == 'true'
        run: |
          set -e
          for c in charts/*; do
            [ -d "$c" ] || continue
            echo "==> helm lint $c"
            helm lint "$c"
          done

      - name: kubeconform validate (helm template)
        if: steps.have_charts.outputs.found == 'true'
        run: |
          set -e
          for c in charts/*; do
            [ -d "$c" ] || continue
            echo "==> kubeconform validate $c"
            if [ -f "$c/values-kind.yaml" ]; then
              helm template "$c" -f "$c/values-kind.yaml" | kubeconform -strict -ignore-missing-schemas -
            else
              helm template "$c" | kubeconform -strict -ignore-missing-schemas -
            fi
          done

      - name: No charts, skip helm/kubeconform
        if: steps.have_charts.outputs.found != 'true'
        run: echo "No charts/ directory or empty; skip helm/kubeconform."
